### ISSUE TITLE
Add support for inline SSML responses

### ISSUE THREAD

**Issue by cameronhunter** [cameronhunter/alexa-lambda-skill#2]
Using [alexa-ssml](https://www.npmjs.com/package/alexa-ssml) (or similar) we could build [SSML](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/speech-synthesis-markup-language-ssml-reference) responses in the same way that React does with JSX.

```javascript
Response.say(<speak>Hello world!</speak>);
```

This would require adding [transform-react-jsx](https://babeljs.io/docs/plugins/transform-react-jsx/) to `plugins` in `.babelrc`:

```json
{
  "presets": ["es2015", "stage-1"],
  "plugins": [
    "transform-decorators-legacy",
    ["transform-react-jsx", { "pragma": "ssml" }]
  ]
}
```

And a change to `Response` to recognize that an SSML object had been passed as text:

```javascript
const outputSpeech = (text, type = PlainText) => {
  if (type === SSML || typeof text === 'object') {
    return { outputSpeech: { type, ssml: (typeof text === 'object') ? renderToString(text) : text } };
  } else {
    return { outputSpeech: { type, text } };
  }
};
```

The issue is that `ava` doesn't compile the tests using the project's `.babelrc` so we would need to compile the tests ourselves. Perhaps a change is needed in `ava` to respect the project's `.babelrc`?

**Comment by nickclaw** [comment]
Hey! Cool that you're thinking about using `alexa-ssml`! Let me know how it works for you and if you have any problems/suggestions.

As for testing, I find it's easiest to stick a `babel-register` before anything (probably using `--require babel-register` in your case). That'll make sure you're testing the same code you deploy to npm without actually having to build every time.

**Comment by cameronhunter** [comment]
Resolved as part of pulling [`Response`](https://github.com/cameronhunter/alexa-response) into its own npm package.
